# Generated by Django 4.0.6 on 2022-07-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Street_Address_1', models.CharField(max_length=255)),
                ('Street_Address_2', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=127)),
                ('State', models.CharField(max_length=2)),
                ('Zip5', models.CharField(max_length=5)),
                ('Country', models.CharField(max_length=63)),
            ],
        ),
    ]
