# Generated by Django 4.0.6 on 2022-07-24 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('physician_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NPI', models.IntegerField(verbose_name='National Provider Identifier')),
                ('Last_Name', models.CharField(max_length=64)),
                ('First_Name', models.CharField(max_length=64)),
                ('MI', models.CharField(max_length=8)),
                ('Credentials', models.CharField(max_length=128)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Entity_Type', models.CharField(choices=[('O', 'Organization'), ('I', 'Individual')], max_length=1)),
                ('MPI', models.CharField(max_length=8, verbose_name='Medicare Participation Indicator')),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='City',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='address',
            name='Country',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='address',
            name='Street_Address_1',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='address',
            name='Street_Address_2',
            field=models.CharField(max_length=256),
        ),
        migrations.AddField(
            model_name='address',
            name='Provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='physician_data.provider'),
        ),
    ]
