# Generated by Django 4.0.6 on 2022-07-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physician_data', '0002_provider_alter_address_city_alter_address_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Street_Address_2',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='MI',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
